const fs = require('fs');

const indexHtml = fs.readFileSync('index.html', 'utf8');

const replacements = [
    { target: '<a href="#services" class="nav-link">Services</a>', replacement: '<a href="#services" class="nav-link" data-translate="nav_services">Services</a>' },
    { target: '<a href="#how-it-works" class="nav-link">How it Works</a>', replacement: '<a href="#how-it-works" class="nav-link" data-translate="nav_how_it_works">How it Works</a>' },
    { target: '<a href="#social" class="nav-link">Our Journey</a>', replacement: '<a href="#social" class="nav-link" data-translate="nav_journey">Our Journey</a>' },
    { target: '<a href="#about" class="nav-link">About</a>', replacement: '<a href="#about" class="nav-link" data-translate="nav_about">About</a>' },
    { target: '<a href="#testimonials" class="nav-link">Reviews</a>', replacement: '<a href="#testimonials" class="nav-link" data-translate="nav_reviews">Reviews</a>' },
    { target: '<a href="#services" class="mobile-link">Services</a>', replacement: '<a href="#services" class="mobile-link" data-translate="nav_services">Services</a>' },
    { target: '<a href="#how-it-works" class="mobile-link">How it Works</a>', replacement: '<a href="#how-it-works" class="mobile-link" data-translate="nav_how_it_works">How it Works</a>' },
    { target: '<a href="#social" class="mobile-link">Our Journey</a>', replacement: '<a href="#social" class="mobile-link" data-translate="nav_journey">Our Journey</a>' },
    { target: '<a href="#about" class="mobile-link">About Us</a>', replacement: '<a href="#about" class="mobile-link" data-translate="nav_about_us">About Us</a>' },
    { target: '<a href="#testimonials" class="mobile-link">Reviews</a>', replacement: '<a href="#testimonials" class="mobile-link" data-translate="nav_reviews">Reviews</a>' },
    { target: '<a href="#" class="mobile-link text-accent open-worker-modal">Join as Worker</a>', replacement: '<a href="#" class="mobile-link text-accent open-worker-modal" data-translate="nav_join_worker">Join as Worker</a>' },
    { target: '<div class="badge badge-glass">We Build & Secure 🏗️🔒</div>', replacement: '<div class="badge badge-glass" data-translate="hero_badge">We Build & Secure 🏗️🔒</div>' },
    { target: '<h1>Trusted Construction & Home Services in One Place</h1>', replacement: '<h1 data-translate="hero_title">Trusted Construction & Home Services in One Place</h1>' },
    { target: '<p>Electricians, Plumbers, Carpenters, Painters, Tile Workers & CCTV Experts — Verified Professionals\r\n                    Near You.</p>', replacement: '<p data-translate="hero_desc">Electricians, Plumbers, Carpenters, Painters, Tile Workers & CCTV Experts — Verified Professionals\r\n                    Near You.</p>' },
    { target: '<p>Electricians, Plumbers, Carpenters, Painters, Tile Workers & CCTV Experts — Verified Professionals\n                    Near You.</p>', replacement: '<p data-translate="hero_desc">Electricians, Plumbers, Carpenters, Painters, Tile Workers & CCTV Experts — Verified Professionals\n                    Near You.</p>' },
    { target: 'Book a Service', replacement: '<span data-translate="hero_book_btn">Book a Service</span>' },
    { target: 'Join as Worker', replacement: '<span data-translate="nav_join_worker">Join as Worker</span>' },
    { target: '<span>Verified Workers</span>', replacement: '<span data-translate="hero_stat_workers">Verified Workers</span>' },
    { target: '<span>Happy Customers</span>', replacement: '<span data-translate="hero_stat_customers">Happy Customers</span>' },
    { target: '<span>Dedicated Support</span>', replacement: '<span data-translate="hero_stat_support">Dedicated Support</span>' },
    { target: '<h2>Premium Services</h2>', replacement: '<h2 data-translate="services_title">Premium Services</h2>' },
    { target: '<p>Expert solutions for every construction and home maintenance need.</p>', replacement: '<p data-translate="services_desc">Expert solutions for every construction and home maintenance need.</p>' },
    { target: '<h3>Electrician</h3>', replacement: '<h3 data-translate="service_electrician">Electrician</h3>' },
    { target: '<p>Wiring, lighting, switchboards, and fault repairs.</p>', replacement: '<p data-translate="service_elec_desc">Wiring, lighting, switchboards, and fault repairs.</p>' },
    { target: '<h3>Plumber</h3>', replacement: '<h3 data-translate="service_plumber">Plumber</h3>' },
    { target: '<p>Pipe installations, leak fixes, bathroom fittings.</p>', replacement: '<p data-translate="service_plumb_desc">Pipe installations, leak fixes, bathroom fittings.</p>' },
    { target: '<h3>Carpenter</h3>', replacement: '<h3 data-translate="service_carpenter">Carpenter</h3>' },
    { target: '<p>Custom furniture, door fittings, wood repairs.</p>', replacement: '<p data-translate="service_carp_desc">Custom furniture, door fittings, wood repairs.</p>' },
    { target: '<h3>Mason</h3>', replacement: '<h3 data-translate="service_mason">Mason</h3>' },
    { target: '<p>Brickwork, plastering, concrete pouring, and structural repairs.</p>', replacement: '<p data-translate="service_mason_desc">Brickwork, plastering, concrete pouring, and structural repairs.</p>' },
    { target: '<h3>Tile Worker</h3>', replacement: '<h3 data-translate="service_tile">Tile Worker</h3>' },
    { target: '<p>Floor and wall tiling, grouting, marble, and granite.</p>', replacement: '<p data-translate="service_tile_desc">Floor and wall tiling, grouting, marble, and granite.</p>' },
    { target: '<h3>Painter</h3>', replacement: '<h3 data-translate="service_painter">Painter</h3>' },
    { target: '<p>Interior/exterior painting, waterproofing, finishes.</p>', replacement: '<p data-translate="service_paint_desc">Interior/exterior painting, waterproofing, finishes.</p>' },
    { target: '<h3>CCTV Installation</h3>', replacement: '<h3 data-translate="service_cctv">CCTV Installation</h3>' },
    { target: '<p>Smart security cameras, DVR setup, and surveillance.</p>', replacement: '<p data-translate="service_cctv_desc">Smart security cameras, DVR setup, and surveillance.</p>' },
    { target: '<h3>Architect</h3>', replacement: '<h3 data-translate="service_architect">Architect</h3>' },
    { target: '<p>Floor plans, 3D elevations, and complete building design.</p>', replacement: '<p data-translate="service_arch_desc">Floor plans, 3D elevations, and complete building design.</p>' },
    { target: '<h3>Engineer</h3>', replacement: '<h3 data-translate="service_engineer">Engineer</h3>' },
    { target: '<p>Site supervision, structural analysis, and project management.</p>', replacement: '<p data-translate="service_eng_desc">Site supervision, structural analysis, and project management.</p>' },
    { target: 'Book Now\r\n                        &rarr;', replacement: '<span data-translate="service_book_btn">Book Now &rarr;</span>' },
    { target: 'Book Now\n                        &rarr;', replacement: '<span data-translate="service_book_btn">Book Now &rarr;</span>' },
    { target: 'Book Now &rarr;', replacement: '<span data-translate="service_book_btn">Book Now &rarr;</span>' },
    { target: '>View All Services</a>', replacement: ' data-translate="services_view_all">View All Services</a>' },
    { target: '<h2>How It Works</h2>', replacement: '<h2 data-translate="how_title">How It Works</h2>' },
    { target: '<p>Getting your work done is simpler than ever.</p>', replacement: '<p data-translate="how_desc">Getting your work done is simpler than ever.</p>' },
    { target: '<h3>Select Service</h3>', replacement: '<h3 data-translate="how_step1_title">Select Service</h3>' },
    { target: '<p>Choose the service you need from our extensive list of professionals.</p>', replacement: '<p data-translate="how_step1_desc">Choose the service you need from our extensive list of professionals.</p>' },
    { target: '<h3>Book Trusted Worker</h3>', replacement: '<h3 data-translate="how_step2_title">Book Trusted Worker</h3>' },
    { target: '<p>Confirm your booking and a verified professional will be assigned instantly.</p>', replacement: '<p data-translate="how_step2_desc">Confirm your booking and a verified professional will be assigned instantly.</p>' },
    { target: '<h3>Get Work Done</h3>', replacement: '<h3 data-translate="how_step3_title">Get Work Done</h3>' },
    { target: '<p>Relax while our expert completes the job safely and securely.</p>', replacement: '<p data-translate="how_step3_desc">Relax while our expert completes the job safely and securely.</p>' },
    { target: 'Follow our Instagram', replacement: '<span data-translate="journey_follow">Follow our Instagram</span>' },
    { target: '<h2 class="font-gradient">Trusted by 50,0+ Customers</h2>', replacement: '<h2 class="font-gradient" data-translate="reviews_title">Trusted by 50,0+ Customers</h2>' },
    { target: '<p>Real stories from homeowners and businesses who rely on VBuilt.</p>', replacement: '<p data-translate="reviews_desc">Real stories from homeowners and businesses who rely on VBuilt.</p>' },
    { target: '<span class="badge badge-primary mb-3">Our Story</span>', replacement: '<span class="badge badge-primary mb-3" data-translate="about_badge">Our Story</span>' },
    { target: '<h2>Why VBuilt Exists</h2>', replacement: '<h2 data-translate="about_title">Why VBuilt Exists</h2>' },
    { target: '<p class="lead-text" style="max-width: 800px; margin: 0 auto;">We noticed a massive gap in India\'s home\r\n                    services market: finding reliable, verified, and transparent skilled professionals was exhausting.\r\n                </p>', replacement: '<p class="lead-text" style="max-width: 800px; margin: 0 auto;" data-translate="about_lead">We noticed a massive gap in India\'s home\r\n                    services market: finding reliable, verified, and transparent skilled professionals was exhausting.\r\n                </p>' },
    { target: '<p class="lead-text" style="max-width: 800px; margin: 0 auto;">We noticed a massive gap in India\'s home\n                    services market: finding reliable, verified, and transparent skilled professionals was exhausting.\n                </p>', replacement: '<p class="lead-text" style="max-width: 800px; margin: 0 auto;" data-translate="about_lead">We noticed a massive gap in India\'s home\n                    services market: finding reliable, verified, and transparent skilled professionals was exhausting.\n                </p>' },
    { target: '<h3 class="mb-3">Building Trust from Zero 🚀</h3>', replacement: '<h3 class="mb-3" data-translate="about_h3">Building Trust from Zero 🚀</h3>' },
    { target: '<p>VBuilt was born from a simple idea: <strong>"We Build & Secure"</strong>. We realized that\r\n                        whether it\'s fixing a leaking pipe, wiring a new home, or installing complex CCTV systems,\r\n                        customers needed someone they could trust with their homes and businesses.</p>', replacement: '<p data-translate="about_p1">VBuilt was born from a simple idea: <strong>"We Build & Secure"</strong>. We realized that\r\n                        whether it\'s fixing a leaking pipe, wiring a new home, or installing complex CCTV systems,\r\n                        customers needed someone they could trust with their homes and businesses.</p>' },
    { target: '<p>VBuilt was born from a simple idea: <strong>"We Build & Secure"</strong>. We realized that\n                        whether it\'s fixing a leaking pipe, wiring a new home, or installing complex CCTV systems,\n                        customers needed someone they could trust with their homes and businesses.</p>', replacement: '<p data-translate="about_p1">VBuilt was born from a simple idea: <strong>"We Build & Secure"</strong>. We realized that\n                        whether it\'s fixing a leaking pipe, wiring a new home, or installing complex CCTV systems,\n                        customers needed someone they could trust with their homes and businesses.</p>' },
    { target: '<p>We are a tech-driven marketplace on a mission to organize the unorganized sector of construction\r\n                        and maintenance. By bringing together the finest tradespeople—electricians, plumbers, masons,\r\n                        and architects—we provide a seamless, transparent, and high-quality service experience.</p>', replacement: '<p data-translate="about_p2">We are a tech-driven marketplace on a mission to organize the unorganized sector of construction\r\n                        and maintenance. By bringing together the finest tradespeople—electricians, plumbers, masons,\r\n                        and architects—we provide a seamless, transparent, and high-quality service experience.</p>' },
    { target: '<p>We are a tech-driven marketplace on a mission to organize the unorganized sector of construction\n                        and maintenance. By bringing together the finest tradespeople—electricians, plumbers, masons,\n                        and architects—we provide a seamless, transparent, and high-quality service experience.</p>', replacement: '<p data-translate="about_p2">We are a tech-driven marketplace on a mission to organize the unorganized sector of construction\n                        and maintenance. By bringing together the finest tradespeople—electricians, plumbers, masons,\n                        and architects—we provide a seamless, transparent, and high-quality service experience.</p>' },
    { target: '<h4>Our Vision</h4>', replacement: '<h4 data-translate="about_vision_title">Our Vision</h4>' },
    { target: '<p>To be the most trusted and reliable partner for every construction and home maintenance\r\n                                need in India.</p>', replacement: '<p data-translate="about_vision_desc">To be the most trusted and reliable partner for every construction and home maintenance\r\n                                need in India.</p>' },
    { target: '<p>To be the most trusted and reliable partner for every construction and home maintenance\n                                need in India.</p>', replacement: '<p data-translate="about_vision_desc">To be the most trusted and reliable partner for every construction and home maintenance\n                                need in India.</p>' },
    { target: '<h4>Our Mission</h4>', replacement: '<h4 data-translate="about_mission_title">Our Mission</h4>' },
    { target: '<p>Empowering skilled workers with fair opportunities while delivering exceptional,\r\n                                frictionless service to customers.</p>', replacement: '<p data-translate="about_mission_desc">Empowering skilled workers with fair opportunities while delivering exceptional,\r\n                                frictionless service to customers.</p>' },
    { target: '<p>Empowering skilled workers with fair opportunities while delivering exceptional,\n                                frictionless service to customers.</p>', replacement: '<p data-translate="about_mission_desc">Empowering skilled workers with fair opportunities while delivering exceptional,\n                                frictionless service to customers.</p>' },
    { target: '<span class="badge badge-primary">For Professionals</span>', replacement: '<span class="badge badge-primary" data-translate="worker_badge">For Professionals</span>' },
    { target: '<h2>Why Workers Join VBuilt</h2>', replacement: '<h2 data-translate="worker_title">Why Workers Join VBuilt</h2>' },
    { target: '<p class="lead-text">We empower skilled tradespeople by providing a platform for consistent growth,\r\n                        respect, and financial stability.</p>', replacement: '<p class="lead-text" data-translate="worker_lead">We empower skilled tradespeople by providing a platform for consistent growth,\r\n                        respect, and financial stability.</p>' },
    { target: '<p class="lead-text">We empower skilled tradespeople by providing a platform for consistent growth,\n                        respect, and financial stability.</p>', replacement: '<p class="lead-text" data-translate="worker_lead">We empower skilled tradespeople by providing a platform for consistent growth,\n                        respect, and financial stability.</p>' },
    { target: 'Register as a Partner', replacement: '<span data-translate="worker_reg_btn">Register as a Partner</span>' },
    { target: '<h2>Ready to get started?</h2>', replacement: '<h2 data-translate="inquiry_title">Ready to get started?</h2>' },
    { target: '<p>Drop your details and our team will call you back within 15 minutes.</p>', replacement: '<p data-translate="inquiry_desc">Drop your details and our team will call you back within 15 minutes.</p>' },
    { target: '>Request\r\n                            Callback</button>', replacement: ' data-translate="inquiry_btn">Request Callback</button>' },
    { target: '>Request\n                            Callback</button>', replacement: ' data-translate="inquiry_btn">Request Callback</button>' },
    { target: '<h3>Company</h3>', replacement: '<h3 data-translate="footer_company">Company</h3>' },
    { target: '<h3>Services</h3>', replacement: '<h3 data-translate="footer_services">Services</h3>' },
    { target: '<h3>Get in Touch</h3>', replacement: '<h3 data-translate="footer_contact">Get in Touch</h3>' },
    { target: '<p>&copy; 2026 VBuilt. All Rights Reserved. Designed for the Future.</p>', replacement: '<p data-translate="footer_rights">&copy; 2026 VBuilt. All Rights Reserved. Designed for the Future.</p>' },
    { target: 'WhatsApp Us', replacement: '<span data-translate="nav_whatsapp">WhatsApp Us</span>' },
    { target: 'Chat on WhatsApp', replacement: '<span data-translate="nav_whatsapp">WhatsApp Us</span>' },
    { target: 'placeholder="Your Name"', replacement: 'placeholder="Your Name" data-translate-placeholder="form_name"' },
    { target: 'placeholder="Phone Number"', replacement: 'placeholder="Phone Number" data-translate-placeholder="form_phone"' },
    { target: '<option value="" disabled selected>Select Service Required</option>', replacement: '<option value="" disabled selected data-translate="form_service">Select Service Required</option>' },
    { target: '<option value="" disabled selected>Select Skill/Profession</option>', replacement: '<option value="" disabled selected data-translate="form_skill">Select Skill/Profession</option>' },
    { target: 'placeholder="Area / Location"', replacement: 'placeholder="Area / Location" data-translate-placeholder="form_loc"' },
    { target: 'placeholder="Years of Experience"', replacement: 'placeholder="Years of Experience" data-translate-placeholder="form_exp"' },
    { target: 'placeholder="Describe your requirement (optional)"', replacement: 'placeholder="Describe your requirement (optional)" data-translate-placeholder="form_desc"' },
    { target: '<h3>Join as <span class="text-accent">Worker</span></h3>', replacement: '<h3 data-translate="modal_worker_title">Join as <span class="text-accent">Worker</span></h3>' },
    { target: '<p>Register to become a verified VBuilt partner and get consistent bookings.</p>', replacement: '<p data-translate="modal_worker_desc">Register to become a verified VBuilt partner and get consistent bookings.</p>' },
    { target: '>Submit\r\n                        Registration</button>', replacement: ' data-translate="modal_worker_btn">Submit Registration</button>' },
    { target: '>Submit\n                        Registration</button>', replacement: ' data-translate="modal_worker_btn">Submit Registration</button>' },
    { target: '<h3>Book <span id="modalServiceName" class="text-accent">Service</span></h3>', replacement: '<h3 data-translate="modal_service_title">Book <span id="modalServiceName" class="text-accent">Service</span></h3>' },
    { target: '<p>Fill out the form below and we\'ll connect you with a verified professional.</p>', replacement: '<p data-translate="modal_service_desc">Fill out the form below and we\'ll connect you with a verified professional.</p>' },
    { target: '>Confirm\r\n                        Booking</button>', replacement: ' data-translate="modal_service_btn">Confirm Booking</button>' },
    { target: '>Confirm\n                        Booking</button>', replacement: ' data-translate="modal_service_btn">Confirm Booking</button>' }
];

let newHtml = indexHtml;
replacements.forEach(r => {
    // Escape string for simple replace
    newHtml = newHtml.split(r.target).join(r.replacement);
});

fs.writeFileSync('index.html', newHtml);
console.log('Replacements completed.');
